[package]
name = "ffs_os_type"
version = "2.3.0"
authors = ["Jan Schulte <janschulte@fastmail.com>", "alexsunxl@163.com"]
license = "MIT"
description = "Detect the operating system type"
repository = "https://github.com/alexsunxl/os_type"

[dependencies]
regex="1"
